return {
    "Breno010L",
    "shawnlovebazuka",
    "ziovxoo",
    "Kay_g4m4",
    "gabi6kkjj",
    "ACNDIEGO",
    "saitama9rsm",
    "Faxcarioca",
    "RUANRODRIGO121121",
    "meka_html",
    "itz_kadu22",
    "Meka_js",
    "shawnloveblazy",
    "sn1ck2r",
    "beatrizz2317",
    "shadow83953",
    "NeoX_neon"
}
